SELECT 
    GETDATE() AS CurrentDateTime,
    SYSDATETIME() AS PreciseDateTime,
    CURRENT_TIMESTAMP AS ANSI_CurrentDateTime,
    SYSDATETIMEOFFSET() AS DateTimeWithOffset,
    SYSUTCDATETIME() AS UTCDateTime,
    GETUTCDATE() as UTCDate;

SELECT CONVERT(VARCHAR(50), CURRENT_TIMESTAMP, 121);
