SELECT * FROM Registration 
WHERE reg_datetime BETWEEN CAST(GETDATE() AS DATE) 
AND DATEADD(MILLISECOND, -3, DATEADD(DAY, 1, CAST(CONVERT(DATE, GETDATE()) AS DATETIME)));

SELECT * FROM Registration 
WHERE reg_datetime >= CAST(GETDATE() AS DATE) 
AND reg_datetime < CAST(DATEADD(DAY, 1, GETDATE()) AS DATE);

SELECT * FROM Registration 
WHERE CAST(reg_datetime AS DATE) = CAST(GETDATE() AS DATE);