SELECT
    FK.TABLE_NAME AS foreign_key_table,
    CU.COLUMN_NAME AS foreign_key_column,
    PK.TABLE_NAME AS referenced_table,
    PT.COLUMN_NAME AS referenced_column,
    C.CONSTRAINT_NAME AS constraint_name
FROM 
    INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS C
JOIN 
    INFORMATION_SCHEMA.TABLE_CONSTRAINTS FK 
    ON C.CONSTRAINT_NAME = FK.CONSTRAINT_NAME
JOIN 
    INFORMATION_SCHEMA.TABLE_CONSTRAINTS PK 
    ON C.UNIQUE_CONSTRAINT_NAME = PK.CONSTRAINT_NAME
JOIN 
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE CU 
    ON C.CONSTRAINT_NAME = CU.CONSTRAINT_NAME
JOIN 
    (
        SELECT 
            i1.TABLE_NAME, i2.COLUMN_NAME 
        FROM 
            INFORMATION_SCHEMA.TABLE_CONSTRAINTS i1
        JOIN 
            INFORMATION_SCHEMA.KEY_COLUMN_USAGE i2 
            ON i1.CONSTRAINT_NAME = i2.CONSTRAINT_NAME
        WHERE 
            i1.CONSTRAINT_TYPE = 'PRIMARY KEY'
    ) PT 
    ON PT.TABLE_NAME = PK.TABLE_NAME
WHERE 
    FK.CONSTRAINT_TYPE = 'FOREIGN KEY'
    AND FK.TABLE_NAME = 'Registration';
