--GETDATE function 
SELECT GETDATE(); 

--CURRENT_TIMESTAMP system defined constant function 
SELECT CURRENT_TIMESTAMP;

--SYSDATETIME function
SELECT SYSDATETIME();

--GETUTCDATE function 
SELECT GETUTCDATE(); 

--SYSUTCDATETIME function
SELECT SYSUTCDATETIME();