--GETDATE function 
SELECT GETUTCDATE(); 

--CURRENT_TIMESTAMP function 
SELECT CURRENT_TIMESTAMP;

--SYSDATETIME function
SELECT SYSDATETIME();

--GETUTCDATE function 
SELECT GETUTCDATE(); 

--SYSUTCDATETIME function
SELECT SYSUTCDATETIME();