START TRANSACTION;
UPDATE DEPARTMENT SET code='MATH' WHERE id=5;
COMMIT;

START TRANSACTION;
INSERT INTO DEPARTMENT(id,name,code) VALUES(6,"Mathematics","MA");
COMMIT;

START TRANSACTION; 
DELETE FROM DEPARTMENT WHERE id=6; 
COMMIT;
